### ISSUE TITLE
Channels are created when click 'Start New Phase'

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2926] opened 2024-05-03 09:30 UTC
## 🐞 Bug description
Channels are created when click 'Start New Phase'

## 🔢 Steps to Reproduce

1. Play game with 'Game Control' role
2. Click 'Start New Phase'
3. Notice some new channel are created
4. Refresh page. new channels are dissapeared

## ⚙️ Expected behavior
No new channel are created when 'Start New Phase'

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/c42490a0-261f-4176-8838-15778aa9772a

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by Tristina1788** [comment] 2024-05-03 09:43
I've found that I raised this ticket before [#2763](https://github.com/serge-web/serge/issues/2763) . @IanMayo Please help me close it.

**Comment by IanMayo** [comment] 2024-05-03 10:04
Closing as duplicate of #2763

**Closed as completed by IanMayo** 2024-05-03 10:04 UTC
Labels: bug
