### ISSUE TITLE
Target disappears for Point Reconnaissance

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1985] opened 2022-10-29 20:49 UTC
[7b92ce8b-e97c-4aea-ad48-aee5aba29cdc.webm](https://user-images.githubusercontent.com/85491794/198851770-5062b1d7-8fd3-4687-962d-47f5a88a2243.webm)

After the first trial, the target pin disappears for Point Reconnaissance. Once it no longer appears, the bug seems to spread to other activities such as area reconnaissance, where I can't specify target area. 

P.S. Point reconnaissance also showed up as Air Activity on the New Message window.

**Comment by IanMayo** [comment] 2022-10-31 15:27
Closing. This appears to be a duplicate of #1987

**Closed as completed by IanMayo** 2022-10-31 15:27 UTC
Labels: bug
